{"node_feature": 1, "neighborhood": ["1113", "1612", "1060", "1794", "1112", "1338", "1247", "1808", "1541", "1426", "1910", "1853", "1526", "1109", "1341", "1644", "1314", "953", "1788", "933", "1752", "1879", "353", "1132", "1715", "1604", "1118", "1042", "1374", "1742", "1721", "1450", "1251", "1037", "1079", "1424", "1580", "1725", "1832", "1629", "1276", "1344", "517", "1091", "907", "1160", "920", "1630", "1361", "1202", "1522", "1433", "1438", "1119", "1128", "1197", "1228", "1463", "1556", "1878", "1560", "1830", "1835", "929", "1082", "1592", "1591", "1674", "366", "1880", "947", "1543", "1302", "1728", "922", "1052", "919", "1151", "1531", "1149", "1249", "1263", "1323", "963", "1285", "1877", "1014", "1163", "962", "1709", "1255", "1697", "1555", "934", "1848", "1692", "1494", "1442", "1658", "1863", "1381", "1230", "1153", "1031", "1477", "1449", "1760", "1179", "1535", "1462", "1039", "1266", "1778", "1350", "1024", "1268", "1453", "1331", "1577", "1016", "1840", "956", "1768", "1093", "1513", "1723", "629", "1735", "1252", "1246", "1200", "1595", "1432", "1614", "1472", "1455", "1653", "1046", "1427", "1871", "1445", "899", "1777", "1510", "950", "1408", "1248", "1820", "1747", "1538", "363", "1287", "961
Unterminated string starting at: line 1 column 1235 (char 1234)
Traceback (most recent call last):
  File "/Users/houyining/Documents/KTH/course/DistributedSystemsAdvanced/id2203-vt24-course-project-graphs/worker.py", line 115, in khop_neighborhood
    data = json.loads(msg)
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1235 (char 1234)





{"node_feature": 93, "neighborhood": ["1661", "1536", "917", "976", "1794", "513", "601", "1790", "1473", "520", "1382", "1638", "1358", "1108", "1512", "1014", "1495", "1751", "1122", "1875", "507", "1778", "1294", "494", "566", "1742", "651", "1894", "567", "1490", "1729", "1631", "1766", "1660", "1204", "1066", "1565", "493", "1018", "535", "614", "1545", "1374", "919", "942", "560", "1870", "1277", "962", "524", "561", "1682", "1677", "1332", "580", "1871", "1475", "1786", "525", "1595", "1313", "1080", "1899", "1543", "1454", "984", "606", "1373", "1427", "1406", "637", "1142", "484", "496", "1611", "1025", "1086", "1245", "1095", "1012", "542", "1320", "1893", "503", "1237", "526", "1850", "506", "1284", "948", "604", "1324", "671", "1812", "1210", "492", "1783", "517", "1574", "553", "1114", "1281", "1102", "1773", "1032", "1429", "500", "1907", "1396", "1113", "1692", "1763", "1625", "1824", "559", "1318", "1878", "1848", "1740", "930", "1744", "1673", "1695", "544", "1828", "1679", "1508", "1487", "1020", "1654", "1261", "596", "641", "1720", "538", "639", "1425", "497", "1645", "1801", "1001", "557", "1694", "1882", "1192", "1616", "514", "591", "1166", "1732", "1706", "1309", "1767", "1158", "1515", "537", "
Unterminated string starting at: line 1 column 1238 (char 1237)
Traceback (most recent call last):
  File "/Users/houyining/Documents/KTH/course/DistributedSystemsAdvanced/id2203-vt24-course-project-graphs/worker.py", line 115, in khop_neighborhood
    data = json.loads(msg)
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1238 (char 1237)





{"node_feature": 93, "neighborhood": ["553", "1778", "1148", "1679", "1625", "503", "1766", "917", "1429", "1282", "563", "601", "1744", "1661", "557", "1303", "954", "506", "1871", "566", "1536", "1751", "1382", "1245", "1294", "1392", "1875", "560", "1763", "1408", "1400", "1631", "1824", "1654", "1357", "494", "1773", "896", "1454", "596", "1574", "1515", "1606", "1692", "1095", "1374", "1014", "526", "1682", "1155", "942", "1565", "1349", "1638", "1025", "930", "1281", "1320", "1660", "1801", "496", "1870", "1783", "1490", "1794", "1475", "604", "1893", "544", "1790", "639", "1210", "1099", "1907", "514", "1012", "669", "1848", "1102", "948", "641", "1122", "1166", "1373", "535", "492", "1284", "487", "1616", "1881", "524", "567", "1694", "537", "1142", "580", "1397", "1487", "520", "484", "1492", "1473", "1645", "1582", "559", "1595", "1086", "517", "1508", "1032", "1732", "1812", "1113", "984", "614", "497", "493", "500", "1309", "1844", "919", "1850", "1611", "1237", "1729", "976", "1313", "1820", "1446", "525", "1677", "1495", "606", "1158", "1324", "1742", "1425", "1427", "1318", "1673", "1300", "1114", "1720", "1514", "1828", "1512", "933", "1332", "507", "1001", "1204", "671", "1786", "1020", "962", "1464", 
Expecting value: line 1 column 1239 (char 1238)
Traceback (most recent call last):
  File "/Users/houyining/Documents/KTH/course/DistributedSystemsAdvanced/id2203-vt24-course-project-graphs/worker.py", line 115, in khop_neighborhood
    data = json.loads(msg)
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1239 (char 1238)





{"node_feature": 93, "neighborhood": ["1773", "1824", "1261", "1080", "933", "1508", "1763", "1881", "591", "1102", "1455", "1113", "1192", "1179", "1682", "671", "1025", "1870", "919", "526", "1740", "496", "520", "513", "1408", "1720", "1899", "559", "669", "524", "1790", "1095", "948", "544", "1284", "1429", "917", "1850", "942", "538", "563", "596", "976", "1875", "1844", "1778", "1677", "1392", "1729", "637", "604", "1086", "1303", "1582", "507", "1332", "1871", "1611", "1210", "1454", "553", "1543", "1514", "1237", "1282", "1425", "1893", "1349", "1595", "514", "1427", "542", "1114", "1661", "1828", "1446", "1545", "930", "936", "1673", "1464", "567", "1638", "1155", "962", "1309", "1281", "1001", "1273", "494", "1767", "503", "493", "566", "1894", "1099", "1320", "1645", "1565", "1679", "1794", "1313", "497", "1680", "1018", "601", "1382", "1158", "1786", "639", "517", "1631", "1300", "1357", "1492", "1032", "984", "1020", "1654", "1142", "527", "1574", "1812", "954", "487", "1512", "535", "1166", "1475", "1536", "1277", "1014", "1606", "1848", "651", "1204", "1294", "1616", "1066", "1732", "1324", "1148", "1358", "1245", "1373", "515", "896", "560", "1751", "1882", "1515", "1374", "1122", "1692", "1318", "641",
Expecting value: line 1 column 1239 (char 1238)
Traceback (most recent call last):
  File "/Users/houyining/Documents/KTH/course/DistributedSystemsAdvanced/id2203-vt24-course-project-graphs/worker.py", line 115, in khop_neighborhood
    data = json.loads(msg)
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1239 (char 1238)





{"node_feature": 93, "neighborhood": ["641", "1606", "1313", "1455", "1192", "1014", "563", "1114", "1166", "1680", "1565", "1210", "494", "1638", "1032", "671", "1303", "1237", "1515", "1158", "526", "1277", "1349", "1848", "942", "1427", "1446", "1261", "984", "1767", "484", "1066", "1245", "1406", "919", "606", "1324", "1122", "651", "1282", "1099", "936", "1142", "497", "1373", "1392", "1429", "506", "1625", "933", "1397", "1732", "507", "637", "1320", "596", "1801", "604", "1742", "515", "1893", "1400", "1396", "1545", "1778", "896", "1104", "1374", "1794", "1875", "535", "1514", "1309", "496", "1783", "1155", "544", "487", "1490", "639", "1536", "1899", "1454", "1495", "1018", "954", "1012", "560", "1492", "1179", "1611", "1679", "1473", "1660", "1682", "1812", "513", "561", "1001", "1108", "1645", "538", "1850", "1661", "1086", "1720", "614", "1706", "1148", "1284", "1512", "1786", "1595", "567", "1844", "1294", "962", "1881", "1616", "557", "1673", "1824", "917", "1828", "1878", "1358", "1281", "1870", "1744", "1357", "500", "1790", "1020", "1332", "1543", "948", "1763", "1273", "1574", "580", "542", "1631", "1102", "553", "1318", "1677", "1025", "930", "566", "537", "1907", "1694", "520", "525", "1692", "591",
Expecting value: line 1 column 1239 (char 1238)
Traceback (most recent call last):
  File "/Users/houyining/Documents/KTH/course/DistributedSystemsAdvanced/id2203-vt24-course-project-graphs/worker.py", line 115, in khop_neighborhood
    data = json.loads(msg)
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1239 (char 1238)





{"node_feature": 93, "neighborhood": ["1786", "954", "1382", "1313", "1812", "1192", "1801", "1893", "1277", "641", "936", "1001", "1740", "1374", "566", "1820", "1400", "1332", "527", "1870", "1773", "484", "1025", "948", "553", "1673", "1427", "639", "1349", "1473", "526", "537", "514", "544", "1324", "1881", "1309", "1742", "1536", "1751", "1320", "1677", "1654", "1179", "500", "1543", "1778", "1490", "1014", "520", "1766", "1099", "1142", "525", "591", "1408", "1166", "1464", "604", "1875", "1294", "507", "1631", "1645", "559", "1638", "1495", "1514", "614", "557", "1487", "1606", "1508", "651", "1512", "1565", "1582", "1425", "1574", "1679", "1406", "1086", "1080", "1744", "1692", "606", "962", "1020", "1694", "1729", "1012", "561", "1878", "1695", "637", "669", "1790", "1882", "1661", "1848", "1720", "984", "503", "1358", "919", "1210", "1204", "567", "1373", "1844", "1108", "1794", "1148", "1155", "1492", "513", "1871", "1018", "1732", "496", "515", "1454", "1545", "1303", "497", "524", "596", "538", "1102", "1114", "1273", "1763", "563", "1850", "580", "1446", "933", "1032", "1824", "1113", "493", "1828", "1357", "487", "506", "1282", "1396", "560", "1397", "930", "1894", "1104", "517", "542", "1783", "1300", "
Unterminated string starting at: line 1 column 1238 (char 1237)
Traceback (most recent call last):
  File "/Users/houyining/Documents/KTH/course/DistributedSystemsAdvanced/id2203-vt24-course-project-graphs/worker.py", line 115, in khop_neighborhood
    data = json.loads(msg)
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1238 (char 1237)





{"node_feature": 93, "neighborhood": ["948", "601", "1408", "559", "1273", "1473", "930", "1400", "1300", "567", "580", "1210", "1309", "506", "896", "1373", "1706", "524", "1382", "497", "487", "1720", "1104", "1122", "1095", "1114", "1543", "503", "596", "1881", "538", "515", "1179", "517", "1744", "1429", "1625", "962", "1812", "507", "494", "933", "1763", "1020", "544", "1732", "936", "566", "1514", "669", "1899", "954", "591", "1086", "557", "537", "942", "1824", "1102", "1882", "492", "1032", "1166", "639", "1695", "1490", "1066", "1396", "1313", "1284", "1320", "604", "1660", "1142", "1680", "1894", "1318", "1871", "1742", "1282", "1406", "1790", "1001", "535", "1080", "496", "1673", "1277", "484", "493", "1631", "637", "1786", "1574", "1113", "1616", "1654", "1427", "560", "1767", "614", "919", "1455", "1204", "1012", "1783", "1801", "1155", "1778", "651", "917", "1515", "1374", "1638", "563", "1014", "1729", "1508", "1679", "606", "1464", "1682", "1740", "1245", "1475", "553", "527", "1606", "1773", "1751", "1907", "1692", "1766", "1099", "1582", "1446", "1820", "1192", "525", "1645", "976", "1425", "1018", "1332", "1454", "1487", "1536", "1025", "1512", "1844", "671", "1875", "1158", "1397", "1848", "1492", "
Unterminated string starting at: line 1 column 1238 (char 1237)
Traceback (most recent call last):
  File "/Users/houyining/Documents/KTH/course/DistributedSystemsAdvanced/id2203-vt24-course-project-graphs/worker.py", line 115, in khop_neighborhood
    data = json.loads(msg)
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1238 (char 1237)





